fixtures:
  repositories:
    staging: 'https://github.com/nanliu/puppet-staging.git'
    transport: 'https://github.com/nanliu/puppet-transport.git'
    vmware_lib: 'https://github.com/vmware/vmware-vmware_lib.git'
  symlinks:
    'vcenter': "#{source_dir}"
